### PR TITLE
Fix for npm use

### PR DESCRIPTION
**Pull request by truongnguyen1912**
When I use it with npm, it show some errors.
- First it could not resolve module `addtocalendar`, it is because main entry in the package.json point to `atc.min.js` which does not exist.
- Second, it throw exception `addtocalendar.load(); is not a function` because callback in the ready function does not return any function.

### CODE REVIEW

**Comment by akrohn** [comment]
Hey there,

shouldn't the fix for the  `addtocalendar.load(); is not a function` problem not be to remove the ready part? I think this is only for JQuery and I'm sure this plugin is not specially for JQuery, but for Javascript.

Just changing the line to:
`addtocalendar.load = function () {`
works for me.

Cheers

**Comment by truongnguyen1912** [comment]
Do you miss something? I don't remove the `ready` part. I just call it.

**Comment by akrohn** [comment]
The load-function is useful to call it from the outside to initialize the plugin.

I think the problem is the "ready", which is JQuery functionality and this plugin has no dependency for JQuery, it's just a plain javascript plugin.

**Comment by atc-master** [comment]
Thank you for pull request! But @akrohn rights, "The load-function is useful to call it from the outside to initialize the plugin.".

**Pull request closed without merging**
